### ISSUE TITLE
Code Smell: Long Methods

### ISSUE THREAD

**Issue by OwenBC** [realjaidhaliwal/JAdventure-Refactoring#2]

**Comment by vijaivir** [comment]
Long Method in: src/main/java/com/jadventure/game/CharacterChange.java
Source Method: [checkForCharacter](https://github.com/realjaidhaliwal/JAdventure-Refactoring/blob/bcc4611450b85a890d67f91a04ce059725b6d43c/src/main/java/com/jadventure/game/CharacterChange.java#L62)
Variable name: highestCharacter

**Comment by OwenBC** [comment]
Didn't realize this would close with PR
